apiVersion : apps/v1
kind: Deployment
metadata:
  name: maanasaazuredevopsproject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maanasaazuredevopsproject
  template:
    metadata:
      labels:
        app: maanasaazuredevopsproject 
    spec:
      containers:
        - name: maanasaazuredevopsproject 
          image: azuredevopsproject.azurecr.io/maanasaazuredevopsproject
          ports:
          - containerPort: 80
